<?xml version="1.0" encoding="utf-8"?><Database Name="LKSDB" Class="LKSDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=194.62.40.24\DATA2;Initial Catalog=LKSDB;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LKSDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LG_120_ITEMS" Member="LG_120_ITEMs">
    <Type Name="LG_120_ITEM">
      <Column Name="LOGICALREF" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ACTIVE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CARDTYPE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CODE" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(51)" CanBeNull="true" />
      <Column Name="STGRPCODE" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="PRODUCERCODE" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
      <Column Name="SPECODE" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="CYPHCODE" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="CLASSTYPE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PURCHBRWS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SALESBRWS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MTRLBRWS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="VAT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PAYMENTREF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRACKTYPE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="LOCTRACKING" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TOOL" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="AUTOINCSL" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DIVLOTSIZE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SHELFLIFE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SHELFDATE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DOMINANTREFS1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOMINANTREFS2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOMINANTREFS3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOMINANTREFS4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOMINANTREFS5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOMINANTREFS6" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOMINANTREFS7" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOMINANTREFS8" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOMINANTREFS9" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOMINANTREFS10" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOMINANTREFS11" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOMINANTREFS12" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IMAGEINC" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TEXTINC" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DEPRTYPE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DEPRRATE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DEPRDUR" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SALVAGEVAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="REVALFLAG" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="REVDEPRFLAG" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PARTDEP" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DEPRTYPE2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DEPRRATE2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DEPRDUR2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="REVALFLAG2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="REVDEPRFLAG2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PARTDEP2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="APPROVED" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="UNITSETREF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QCCSETREF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DISTAMOUNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CAPIBLOCK_CREATEDBY" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CAPIBLOCK_CREADEDDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CAPIBLOCK_CREATEDHOUR" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CAPIBLOCK_CREATEDMIN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CAPIBLOCK_CREATEDSEC" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CAPIBLOCK_MODIFIEDBY" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CAPIBLOCK_MODIFIEDDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CAPIBLOCK_MODIFIEDHOUR" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CAPIBLOCK_MODIFIEDMIN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CAPIBLOCK_MODIFIEDSEC" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SITEID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="RECSTATUS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ORGLOGICREF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UNIVID" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="DISTLOTUNITS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="COMBLOTUNITS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="WFSTATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DISTPOINT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CAMPPOINT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CANUSEINTRNS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ISONR" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="GROUPNR" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="PRODCOUNTRY" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="ADDTAXREF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QPRODAMNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QPRODUOM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QPRODSRCINDEX" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EXTACCESSFLAGS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PACKET" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SALVAGEVAL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SELLVAT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RETURNVAT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LOGOID" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="LIDCONFIRMED" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="GTIPCODE" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="EXPCTGNO" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="B2CCODE" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="MARKREF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IMAGE2INC" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="AVRWHDURATION" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EXTCARDFLAGS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MINORDAMOUNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FREIGHTPLACE" Type="System.String" DbType="VarChar(51)" CanBeNull="true" />
      <Column Name="FREIGHTTYPCODE1" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="FREIGHTTYPCODE2" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="FREIGHTTYPCODE3" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="FREIGHTTYPCODE4" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="FREIGHTTYPCODE5" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="FREIGHTTYPCODE6" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="FREIGHTTYPCODE7" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="FREIGHTTYPCODE8" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="FREIGHTTYPCODE9" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="FREIGHTTYPCODE10" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="STATECODE" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="STATENAME" Type="System.String" DbType="VarChar(41)" CanBeNull="true" />
      <Column Name="EXPCATEGORY" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="LOSTFACTOR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TEXTINCENG" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EANBARCODE" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="DEPRCLASSTYPE" Type="System.String" DbType="VarChar(31)" CanBeNull="true" />
      <Column Name="WFLOWCRDREF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SELLPRVAT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RETURNPRVAT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LOWLEVELCODES1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOWLEVELCODES2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOWLEVELCODES3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOWLEVELCODES4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOWLEVELCODES5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOWLEVELCODES6" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOWLEVELCODES7" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOWLEVELCODES8" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOWLEVELCODES9" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOWLEVELCODES10" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ORGLOGOID" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="QPRODDEPART" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CANCONFIGURE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CHARSETREF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CANDEDUCT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CONSCODEREF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SPECODE2" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="SPECODE3" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="SPECODE4" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="SPECODE5" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="EXPENSE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ORIGIN" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="NAME2" Type="System.String" DbType="VarChar(51)" CanBeNull="true" />
      <Column Name="COMPKDVUSE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="USEDINPERIODS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EXIMTAX1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EXIMTAX2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EXIMTAX3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EXIMTAX4" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EXIMTAX5" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRODUCTLEVEL" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="APPSPEVATMATRAH" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="NAME3" Type="System.String" DbType="VarChar(201)" CanBeNull="true" />
      <Column Name="FACOSTKEYS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="KKLINESDISABLE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="APPROVE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="APPROVEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GLOBALID" Type="System.String" DbType="VarChar(51)" CanBeNull="true" />
      <Column Name="SALEDEDUCTPART1" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SALEDEDUCTPART2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PURCDEDUCTPART1" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PURCDEDUCTPART2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CATEGORYID" Type="System.String" DbType="VarChar(51)" CanBeNull="true" />
      <Column Name="CATEGORYNAME" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="KEYWORD1" Type="System.String" DbType="VarChar(121)" CanBeNull="true" />
      <Column Name="KEYWORD2" Type="System.String" DbType="VarChar(121)" CanBeNull="true" />
      <Column Name="KEYWORD3" Type="System.String" DbType="VarChar(121)" CanBeNull="true" />
      <Column Name="KEYWORD4" Type="System.String" DbType="VarChar(121)" CanBeNull="true" />
      <Column Name="KEYWORD5" Type="System.String" DbType="VarChar(121)" CanBeNull="true" />
      <Column Name="GUID" Type="System.String" DbType="VarChar(37)" CanBeNull="true" />
      <Column Name="DEMANDMEETSORTFLD1" Type="System.String" DbType="VarChar(51)" CanBeNull="true" />
      <Column Name="DEMANDMEETSORTFLD2" Type="System.String" DbType="VarChar(51)" CanBeNull="true" />
      <Column Name="DEMANDMEETSORTFLD3" Type="System.String" DbType="VarChar(51)" CanBeNull="true" />
      <Column Name="DEMANDMEETSORTFLD4" Type="System.String" DbType="VarChar(51)" CanBeNull="true" />
      <Column Name="DEMANDMEETSORTFLD5" Type="System.String" DbType="VarChar(51)" CanBeNull="true" />
      <Column Name="DEDUCTCODE" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="PROJECTREF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAME4" Type="System.String" DbType="VarChar(201)" CanBeNull="true" />
      <Column Name="QPRODSUBAMNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QPRODSUBUOM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QPRODSUBSRCINDEX" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="QPRODSUBDEPART" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PORDAMNTTOLERANCE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SORDAMNTTOLERANCE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MULTIADDTAX" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CPACODE" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="PUBLICCOUNTRYREF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FAUSEFULLIFECODE" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="FAUSEFULLIFECODE2" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="MOLD" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MOLDLIFETRACKTYPE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MOLDUSAGELIFE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MOLDFACTOR" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MOLDMAINTNUMBER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MOLDMAINTLIFETYPE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MOLDMAINTLIFE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MOLDLIFEASRATIO" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MOLDMAINTPERUNIT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="OBTAINTYPE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MOLDMAINTPERIOD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MOLDMAINTTYPE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MOLDMAINTBEGDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NODISCOUNT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="LEVELCONTROL" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SALESLIMITQUANTITY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GAINTYPE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="FORECASTCODE" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LG_120_UNITBARCODE" Member="LG_120_UNITBARCODEs">
    <Type Name="LG_120_UNITBARCODE">
      <Column Name="LOGICALREF" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ITMUNITAREF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ITEMREF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VARIANTREF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UNITLINEREF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LINENR" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BARCODE" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
      <Column Name="SITEID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="RECSTATUS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ORGLOGICREF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TYP" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="WBARCODESHIFT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="GLOBALID" Type="System.String" DbType="VarChar(51)" CanBeNull="true" />
      <Column Name="CAPIBLOCK_CREATEDBY" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CAPIBLOCK_CREADEDDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CAPIBLOCK_CREATEDHOUR" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CAPIBLOCK_CREATEDMIN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CAPIBLOCK_CREATEDSEC" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CAPIBLOCK_MODIFIEDBY" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CAPIBLOCK_MODIFIEDDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CAPIBLOCK_MODIFIEDHOUR" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CAPIBLOCK_MODIFIEDMIN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CAPIBLOCK_MODIFIEDSEC" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
</Database>